### ISSUE TITLE
Implementación servidor express.

### ISSUE THREAD

**Issue by jomaher** [SOS1617/SOS1617-12#9]
- [x] 1. Tener un el repositorio del grupo (SOS1617-XX) el código de un servidor express listo para ser lanzado que tenga un recurso configurado de forma que cuando se solicite el acceso a “/time”, devuelva el dia y hora actual del servidor en el formato: “1st March of 2017 , 08:35:00”. 
- [x] 2. NO se debe añadir la carpeta node_modules al control de versiones git. 
Para ignorar la carpeta “node_modules” en git metiendola en el archivo “.gitignore” (ver ejemplo)

**Comment by jomaher** [comment]
He implementado el servidor y he hecho push del repositorio.
No he implementado: 

>  cuando se solicite el acceso a “/time”, devuelva el día y hora actual del servidor en el formato: “1st March of 2017, 08:35:00”.

**Comment by heliogm1** [comment]
Ya está el recurso "“/time” usando el módulo dateformat
